name: SCA Check with Build
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
jobs:
  sca:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    
    - name: Build with Maven
      run: mvn clean package
    
    - name: Create project zip
      run: zip -r project.zip . -x "*.git*"
    
    - name: Perform SCA Scan
      run: |
        RESPONSE=$(curl -X POST \
          -H "Client-ID: ${{ secrets.INTRUCEPT_CLIENT_ID }}" \
          -H "Client-Secret: ${{ secrets.INTRUCEPT_CLIENT_SECRET }}" \
          -F "projectZipFile=@project.zip" \
          -F "applicationId=${{ secrets.INTRUCEPT_APPLICATION_ID }}" \
          -F "scanName=SCA Scan from GitHub Actions" \
          -F "language=java" \
          https://appsecops-api.intruceptlabs.com/api/v1/integrations/sca-scans)
        
        echo "SCA Response:"
        VULNS_TABLE=$(echo "$RESPONSE" | jq -r '.vulnsTable // .dependenciesTable')
        if [ "$VULNS_TABLE" != "null" ] && [ -n "$VULNS_TABLE" ]; then
          echo "$VULNS_TABLE"
        else
          echo "No SCA vulnerabilities found."
        fi
        
        CAN_PROCEED=$(echo $RESPONSE | jq -r '.canProceed')
        echo "canProceed=$CAN_PROCEED" >> $GITHUB_ENV
    
    - name: Check SCA result
      if: env.canProceed != 'true'
      run: |
        echo "SCA scan failed. Build cancelled."
        exit 1
    
    - name: Rebuild with Maven
      if: env.canProceed == 'true'
      run: mvn clean package
    
    - name: Upload artifact
      if: env.canProceed == 'true'
      uses: actions/upload-artifact@v3
      with:
        name: sca-project-files
        path: target/*.jar
